# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch data
        uses: actions/github-script@v5
        id: set-result
        with:
          script: |
            const script = require('./_actions/fetchData.js');
            const data = await script({ github, context, core });
            return data;
          result-encoding: string
      - name: Push data
        run: |
          echo '${{steps.set-result.outputs.result}}' > ./docs/data.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./docs/data.json
          git commit -m "automated data"
          git push
