# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/github-script@v5
        id: set-result
        with:
          script: |
            const fs = require('fs');
            const query = `query($owner:String!, $name:String!) {
              repository(owner:$owner, name:$name){
                issues(first:100) {
                  nodes {
                    id,
                    title,
                    body,
                    publishedAt,
                    url,
                    number,
                    labels(first:10) {
                      nodes {
                        name
                      }
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo
            }
            const result = await github.graphql(query, variables)
            const output = JSON.stringify(result?.repository?.issues?.nodes, null, 2)
            console.log('output', output);
            return output
          result-encoding: string
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push data
        run: |
          echo '${{steps.set-result.outputs.result}}' > ./docs/data.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./docs/data.json
          git commit -m "automated data"
          git push
