# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const query = `query($owner:String!, $name:String!) {
              repository(owner:$owner, name:$name){
                issues(first:100) {
                  nodes {
                    id,
                    title
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo
            }
            const result = await github.graphql(query, variables)
            const output = JSON.stringify(result, null, 2);
            console.log(output)
            fs.writeFileSync('./data.json', output, 'utf8')
      - name: Use
        uses: actions/checkout@v2
      - name: Commit data file
        run: |
          git config --global user.name '9am'
          git config --global user.email 'gbgogb@gmail.com'
          git commit -am "Automated data"
          git push
